/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export function sum(a: number, b: number): number
export class JsRepeater {
  constructor(callback1: (...args: any[]) => any, callback2: (...args: any[]) => any)
}
